# Generated by Django 4.0 on 2022-07-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHECKINOUT',
            fields=[
                ('CHECKTIME', models.DateTimeField()),
                ('CHECKTYPE', models.CharField(max_length=100)),
                ('USERID', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CHECKINOUT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='USERINFO',
            fields=[
                ('USERID', models.IntegerField(primary_key=True, serialize=False)),
                ('BADGENUMBER', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'USERINFO',
                'managed': False,
            },
        ),
    ]
